### ISSUE TITLE
Module build failed: Error: Options passed to index.js which does not accept options. 

### ISSUE THREAD

**Issue by wayneconnolly** [anmatika/poloniex-api-gui#1]
Hi @anmatika , Great work on the api, cli and gui!

So my API keys and pre-reqs (node 6.7.0, yarn, npm i poloniex-api) have been added and the below results on yarn start.

```
Module build failed: Error: Options {"targets":{"ie":9,"uglify":true},"useBuiltIns":false,"modules":false} passed to /root/poloniex-api-gui-maste
r/node_modules/babel-preset-env/lib/index.js which does not accept options.                                                                          
     at Array.map (native)
     at Array.map (native)
```

Similar error here: https://github.com/babel/babel-preset-env/issues/10

Note: your cli with the same api keys works perfectly and very fast.

**Comment by anmatika** [comment]
Hi Wayne, thank you!

I guess you are on Windows.
Actually I haven't tested this on Windows before, however, I was able to reproduce this and it seems the error happens on that OS only. I am currently looking for the solution to fix this.

**Comment by anmatika** [comment]
Okay it should be fixed now. 

Please do 
```` git pull ````
```` yarn upgrade ````

Or just clone the repo again in the fresh folder
and ````yarn install````

and finally just start it with ```` yarn start ````

Please let me know if you still have issues with this.

**Comment by wayneconnolly** [comment]
My error above was from Ubuntu. (see /root) I tried on both Ubuntu and Windows. Failed on both. 

It works now! Confirmed. Ill close this.
