### ISSUE TITLE
poloniex now supports push API

### ISSUE THREAD

**Issue by wayneconnolly** [anmatika/poloniex-api-gui#2]
Hello @anmatika , Just a suggestion/enhancement, but your gui may benefit by having the push API auto update the data. See below:

> Node.js example of how to connect to the push API (requires autobahn): http://pastebin.com/dMX7mZE0
> 
> Push API
> The best way to get public data updates on markets is via the push API, which pushes live ticker, order book, trade, and Trollbox updates over WebSockets using the WAMP protocol. In order to use the push API, connect to wss://api.poloniex.com and subscribe to the desired feed.

**Comment by anmatika** [comment]
Hello Wayne, thanks for suggestion. I think could implement that in the near future. Actually https://github.com/anmatika/poloniex-api#2-push-api supports it already. Just haven't utilized it in the GUI yet.

**Comment by wayneconnolly** [comment]
Cool, I looked through the code and couldn't see it. Sorry for the noise :+1: 

You would only need it attached to returnTicker() to start with I'd imagine.

**Comment by anmatika** [comment]
Ticker automatic update feature through the push api now added.

**Comment by wayneconnolly** [comment]
Brilliant!
